export const METADATA = {
  author: 'Anas Pirzada',
  title:
    'Hire Full Stack Developer | Fix Broken Web Apps & Build Startup Ideas | Anas Pirzada',
  description:
    'Trusted by 50+ clients worldwide. Anas Pirzada is a full stack developer who fixes broken React/Next.js apps and builds startup products from scratch. 5★ rated. Free 30-min consultation.',
  siteUrl: 'https://anaspirzada.vercel.app/',
  twitterHandle: '@Anas_Pirzada1',
  keywords: [
    'hire full stack developer',
    'fix broken web app',
    'build startup idea',
    'hire React developer',
    'Next.js developer for hire',
    'freelance React developer',
    'startup MVP development',
    'vibe coding fix',
    'web app debugging',
    'full stack development services',
    'hire web developer',
    'web app development company',
    'Anas Pirzada',
    'React.js developer',
    'Next.js specialist',
    'Node.js developer',
    'Python developer',
    'Laravel developer',
    'Django developer',
    'Firebase developer',
    'MongoDB developer',
    'AI integration developer',
    'fix my app developer',
    'build my app developer',
  ].join(', '),
  image:
    'https://res.cloudinary.com/di6tubsu9/image/upload/v1737926697/jb3dfhw9wxmozff6j56w.png',
  language: 'English',
  themeColor: '#000000',
};
