export const METADATA = {
  author: 'Anas Pirzada',
  title:
    'Anas Pirzada - Full Stack Developer & AI Expert | React.js & Next.js Specialist',
  description:
    'Anas Pirzada is a Full Stack Developer and AI Expert specializing in React.js, Next.js, and Machine Learning. With 5+ years of experience, he creates scalable web applications and AI-powered solutions. View his portfolio of modern web projects.',
  siteUrl: 'https://anaspirzada.vercel.app/',
  twitterHandle: '@Anas_Pirzada1',
  keywords: [
    'Anas Pirzada',
    'Full Stack Developer',
    'Frontend Engineer',
    'AI Expert',
    'Machine Learning Developer',
    'React.js Developer',
    'Next.js Specialist',
    'Software Engineer',
    'Web Developer',
    'JavaScript Developer',
    'TypeScript Developer',
    'Node.js Developer',
    'Python Developer',
    'AI Integration',
    'Portfolio',
    'Web Development Services',
    'Modern Web Solutions',
    'Responsive Web Design',
    'UI/UX Developer',
    'Laravel Developer',
    'Django Developer',
    'Firebase Developer',
    'MongoDB Developer',
    'MySQL Developer',
  ].join(', '),
  image:
    'https://res.cloudinary.com/di6tubsu9/image/upload/v1737926697/jb3dfhw9wxmozff6j56w.png',
  language: 'English',
  themeColor: '#000000',
};
